version: '3.1'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: member
      MYSQL_USER: member_api
      MYSQL_PASSWORD: member_api!
      MYSQL_ROOT_PASSWORD: member_api!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
